/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 tp.gltf --transform
Author: Petru Grati (https://sketchfab.com/einmeister5)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/trandafir-weaponcraft-2023-bf26b804989f4f86adbe99de21274d6a
Title: Trandafir - WeaponCraft 2023
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/tp-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={6.02} position={[0, 2.00, -0.13]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.RoseSword002_sword_0.geometry} material={materials.sword} rotation={[-Math.PI / 2, -1.22, 0]} scale={34.92} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/tp-transformed.glb')
